// apps/vue2/src/components/MeshlineBackground.vue
<template>
  <div class="pointer-events-none absolute inset-0 overflow-hidden bg-[#eef3f8]" aria-hidden="true">
    <!-- Fine + Coarse Grid -->
    <div class="grid-field absolute inset-0" />
    <div class="grid-field-lg absolute inset-0" />

    <!-- Radar Rings anchored in the center -->
    <div class="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 pointer-events-none">
      <span
        v-for="i in 3"
        :key="i"
        class="absolute left-0 top-0 h-[620px] w-[620px] -translate-x-1/2 -translate-y-1/2 rounded-full border border-[#0b5cff]/25 animate-radar-pulse"
        :style="{ animationDelay: `${(i - 1) * 2}s` }"
      />
      <span class="absolute left-0 top-0 h-[400px] w-[400px] -translate-x-1/2 -translate-y-1/2 rounded-full border border-[#0b5cff]/20" />
      <span class="absolute left-0 top-0 h-[760px] w-[760px] -translate-x-1/2 -translate-y-1/2 rounded-full border border-[#0b5cff]/10" />
    </div>

    <!-- Mesh Network Lines -->
    <svg viewBox="0 0 100 100" preserveAspectRatio="none" class="absolute inset-0 h-full w-full">
      <template v-for="link in meshlineLinks">
        <line
          v-if="nodeById(link.from) && nodeById(link.to)"
          :key="`${link.from}-${link.to}`"
          :x1="nodeById(link.from).x"
          :y1="nodeById(link.from).y"
          :x2="nodeById(link.to).x"
          :y2="nodeById(link.to).y"
          stroke="#0b5cff"
          stroke-opacity="0.25"
          stroke-width="1"
          vector-effect="non-scaling-stroke"
        />
      </template>
    </svg>

    <!-- Dynamic Telemetry Packet Flow -->
    <svg class="absolute inset-0 h-full w-full">
      <template v-for="(link, index) in meshlinePacketLinks">
        <circle
          v-if="nodeById(link.from) && nodeById(link.to)"
          :key="`packet-${link.from}-${link.to}`"
          r="3"
          fill="#0b5cff"
          :cx="`${nodeById(link.from).x}%`"
          :cy="`${nodeById(link.from).y}%`"
          opacity="0"
        >
          <animate
            attributeName="cx"
            :values="`${nodeById(link.from).x}%; ${nodeById(link.to).x}%`"
            keyTimes="0; 1"
            dur="3.2s"
            :begin="`${index * 0.7}s`"
            repeatCount="indefinite"
          />
          <animate
            attributeName="cy"
            :values="`${nodeById(link.from).y}%; ${nodeById(link.to).y}%`"
            keyTimes="0; 1"
            dur="3.2s"
            :begin="`${index * 0.7}s`"
            repeatCount="indefinite"
          />
          <animate
            attributeName="opacity"
            values="0; 0.95; 0.95; 0"
            keyTimes="0; 0.15; 0.85; 1"
            dur="3.2s"
            :begin="`${index * 0.7}s`"
            repeatCount="indefinite"
          />
        </circle>
      </template>
    </svg>

    <!-- Mesh Nodes Layer -->
    <div
      v-for="(node, index) in meshlineNodes"
      :key="node.id"
      class="absolute -translate-x-1/2 -translate-y-1/2"
      :style="{ left: `${node.x}%`, top: `${node.y}%` }"
    >
      <span
        class="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 rounded-full animate-ping opacity-20"
        :style="{
          width: `${meshlineNodeRadius[node.size] * 10}px`,
          height: `${meshlineNodeRadius[node.size] * 10}px`,
          backgroundColor: meshlineStatusColor[node.status],
          animationDuration: '4s',
          animationDelay: `${index * 0.35}s`
        }"
      />

      <span
        class="relative block rounded-full bg-white shadow-sm"
        :style="{
          width: `${meshlineNodeRadius[node.size] * 4}px`,
          height: `${meshlineNodeRadius[node.size] * 4}px`,
          border: `${node.size === 'leaf' ? 1.5 : 2}px solid ${meshlineStatusColor[node.status]}`
        }"
      />

      <template v-if="node.size === 'hub'">
        <span
          class="absolute left-1/2 top-1/2 h-px w-16 -translate-x-1/2 -translate-y-1/2"
          :style="{ backgroundColor: meshlineStatusColor[node.status], opacity: 0.3 }"
        />
        <span
          class="absolute left-1/2 top-1/2 h-16 w-px -translate-x-1/2 -translate-y-1/2"
          :style="{ backgroundColor: meshlineStatusColor[node.status], opacity: 0.3 }"
        />
      </template>
    </div>

    <!-- Vertical Scan Sweep -->
    <div class="scan-line absolute inset-x-0 h-44 opacity-40 animate-scan-sweep" />

    <!-- Corner Tech Brackets -->
    <span class="absolute h-8 w-8 border-[#0b5cff]/35 left-6 top-6 border-l-2 border-t-2" />
    <span class="absolute h-8 w-8 border-[#0b5cff]/35 right-6 top-6 border-r-2 border-t-2" />
    <span class="absolute h-8 w-8 border-[#0b5cff]/35 left-6 bottom-6 border-b-2 border-l-2" />
    <span class="absolute h-8 w-8 border-[#0b5cff]/35 right-6 bottom-6 border-b-2 border-r-2" />

    <!-- Edge Soft Fade -->
    <div class="absolute inset-0 bg-[#eef3f8]/40" />
  </div>
</template>

<script>
import {
  meshlineLinks,
  meshlineNodes,
  meshlinePacketLinks,
  meshlineNodeRadius,
  meshlineStatusColor
} from '@login-hub/shared-data';

export default {
  name: 'MeshlineBackground',
  data() {
    return {
      meshlineLinks,
      meshlineNodes,
      meshlinePacketLinks,
      meshlineNodeRadius,
      meshlineStatusColor
    };
  },
  methods: {
    nodeById(id) {
      return meshlineNodes.find((node) => node.id === id);
    }
  }
};
</script>

// apps/react/src/components/MeshlineBackground.tsx
import React from 'react';
import { motion, useReducedMotion } from 'framer-motion';
import {
  meshlineLinks,
  meshlineNodes,
  meshlinePacketLinks,
  meshlineNodeRadius,
  meshlineStatusColor
} from '@login-hub/shared-data';

function nodeById(id: string) {
  return meshlineNodes.find((node) => node.id === id);
}

export function MeshlineBackground() {
  const reduceMotion = useReducedMotion();

  return (
    <div className="pointer-events-none absolute inset-0 overflow-hidden bg-[#eef3f8]" aria-hidden="true">
      {/* Fine + Coarse Grid */}
      <div className="grid-field absolute inset-0" />
      <div className="grid-field-lg absolute inset-0" />

      {/* Radar Rings anchored in the center */}
      <div className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 pointer-events-none">
        {!reduceMotion &&
          [0, 1, 2].map((index) => (
            <motion.span
              key={index}
              className="absolute left-0 top-0 h-[620px] w-[620px] -translate-x-1/2 -translate-y-1/2 rounded-full border border-[#0b5cff]/25"
              animate={{ scale: [0.45, 1.25], opacity: [0.45, 0] }}
              transition={{ duration: 6, ease: 'linear', repeat: Infinity, delay: index * 2 }}
            />
          ))}
        <span className="absolute left-0 top-0 h-[400px] w-[400px] -translate-x-1/2 -translate-y-1/2 rounded-full border border-[#0b5cff]/20" />
        <span className="absolute left-0 top-0 h-[760px] w-[760px] -translate-x-1/2 -translate-y-1/2 rounded-full border border-[#0b5cff]/10" />
      </div>

      {/* Mesh Network Lines */}
      <svg viewBox="0 0 100 100" preserveAspectRatio="none" className="absolute inset-0 h-full w-full">
        {meshlineLinks.map((link) => {
          const from = nodeById(link.from);
          const to = nodeById(link.to);
          if (!from || !to) return null;
          return (
            <line
              key={`${link.from}-${link.to}`}
              x1={from.x}
              y1={from.y}
              x2={to.x}
              y2={to.y}
              stroke="#0b5cff"
              strokeOpacity={0.25}
              strokeWidth={1}
              vectorEffect="non-scaling-stroke"
            />
          );
        })}
      </svg>

      {/* Dynamic Telemetry Packet Flow */}
      {!reduceMotion && (
        <svg className="absolute inset-0 h-full w-full">
          {meshlinePacketLinks.map((link, index) => {
            const from = nodeById(link.from);
            const to = nodeById(link.to);
            if (!from || !to) return null;
            return (
              <motion.circle
                key={`packet-${link.from}-${link.to}`}
                r={3}
                fill="#0b5cff"
                initial={{ opacity: 0 }}
                animate={{
                  cx: [`${from.x}%`, `${to.x}%`],
                  cy: [`${from.y}%`, `${to.y}%`],
                  opacity: [0, 0.95, 0.95, 0]
                }}
                transition={{ duration: 3.2, ease: 'linear', repeat: Infinity, delay: index * 0.7 }}
              />
            );
          })}
        </svg>
      )}

      {/* Mesh Nodes Layer */}
      {meshlineNodes.map((node, index) => {
        const size = meshlineNodeRadius[node.size];
        const color = meshlineStatusColor[node.status];
        return (
          <div
            key={node.id}
            className="absolute -translate-x-1/2 -translate-y-1/2"
            style={{ left: `${node.x}%`, top: `${node.y}%` }}
          >
            {!reduceMotion && (
              <motion.span
                className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 rounded-full"
                style={{ width: size * 12, height: size * 12, backgroundColor: color }}
                animate={{ opacity: [0.15, 0.02, 0.15], scale: [0.7, 1.15, 0.7] }}
                transition={{ duration: 4, ease: 'easeInOut', repeat: Infinity, delay: index * 0.35 }}
              />
            )}

            <span
              className="relative block rounded-full bg-white shadow-sm"
              style={{
                width: size * 4,
                height: size * 4,
                border: `${node.size === 'leaf' ? 1.5 : 2}px solid ${color}`
              }}
            />

            {node.size === 'hub' && (
              <>
                <span
                  className="absolute left-1/2 top-1/2 h-px w-16 -translate-x-1/2 -translate-y-1/2"
                  style={{ backgroundColor: color, opacity: 0.3 }}
                />
                <span
                  className="absolute left-1/2 top-1/2 h-16 w-px -translate-x-1/2 -translate-y-1/2"
                  style={{ backgroundColor: color, opacity: 0.3 }}
                />
              </>
            )}
          </div>
        );
      })}

      {/* Vertical Scan Sweep */}
      {!reduceMotion && (
        <motion.div
          className="scan-line absolute inset-x-0 h-44 opacity-40"
          animate={{ y: ['-12%', '112%'] }}
          transition={{ duration: 11, ease: 'linear', repeat: Infinity }}
        />
      )}

      {/* Corner Tech Brackets */}
      {[
        'left-6 top-6 border-l-2 border-t-2',
        'right-6 top-6 border-r-2 border-t-2',
        'left-6 bottom-6 border-b-2 border-l-2',
        'right-6 bottom-6 border-b-2 border-r-2'
      ].map((corner) => (
        <span key={corner} className={`absolute h-8 w-8 border-[#0b5cff]/35 ${corner}`} />
      ))}

      {/* Edge Soft Fade */}
      <div className="absolute inset-0 bg-[#eef3f8]/40" />
    </div>
  );
}
